/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author d7392
 * @date 15-05-2019 15.32
 */
import static ratpack.groovy.Groovy.ratpack

ratpack {
	// cors headers
	include 'modules/cors.groovy'

	// error handling
	include 'modules/error-handler.groovy'

	// external file conf
	include 'modules/server-config.groovy'

	// fake business logic module
	include 'modules/business-stub.groovy'

	// logging (have to be the last one)
	include 'modules/request-log.groovy'
}
