/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author d7392
 * @date 15-05-2019 15.32
 */
// external
import static ratpack.groovy.Groovy.ratpack
import ratpack.handling.RequestLogger
// internal

ratpack {
	handlers {
		// Here we use the of method to implement
		// custom request logging.
		all(RequestLogger.of { outcome ->
			// Only log when logger is enabled.
			if (RequestLogger.LOGGER.infoEnabled) {
				// Log how long the request handling took.
				RequestLogger.LOGGER.info (
					'{} "{} {} {}" served in {}.{} seconds.',
					outcome.request.timestamp,
					outcome.request.method,
					outcome.request.rawUri,
					outcome.request.protocol,
					outcome.duration.seconds,
					outcome.duration.nano
				)
			}
		})
	}
}
