/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author d7392
 * @date 15-05-2019 15.32
 */
// external
import static ratpack.groovy.Groovy.ratpack
import ratpack.handling.RequestLogger
// internal

ratpack {
	handlers {
		all(RequestLogger.ncsa())
	}
}
