/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author d7392
 * @date 15-05-2019 15.32
 *
 * Example conf class
 * ------------------
 * class YextApi {
 *   String key
 *   String url
 * }
 *
 * Corresponding env variables
 * ---------------------------
 * export RATPACK_YEXT__API__KEY='123abcd'
 * export RATPACK_YEXT__API__URL='https://api.yext.com/v2'
 */
// external
import static ratpack.groovy.Groovy.ratpack
// internal

ratpack {
	serverConfig {
		env()
		//require("/yext/api", YextApi)
	}
}
